name: Deploy to HostGator via FTP

on:
  push:
    branches:
      - master  

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner를 사용합니다.
    steps:
    - uses: actions/checkout@v2  # 저장소를 체크아웃합니다.

    - name: FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.oqf.fnh.temporary.site  # FTP 서버 주소
        username: ${{ secrets.FTP_USERNAME }}  # FTP 사용자 이름
        password: ${{ secrets.FTP_PASSWORD }}  # FTP 비밀번호
        local-dir: ./  # 로컬 디렉토리 설정, 여기서는 전체 저장소
        server-dir: /home3/oqffnhte/public_html/  # 서버의 타겟 디렉토리

